--- #YAML:1.0
name:               App-PS3MEncoder
version:            0.5
abstract:           MEncoder wrapper for PS3 Media Server
author:
    - chocolateboy <chocolate@cpan.org>
license:            artistic_2
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    IO::All:          0
    IPC::Cmd:         0.54
    List::MoreUtils:  0
    LWP::Simple:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
