---
abstract: 'MEncoder wrapper for PS3 Media Server'
author:
  - 'chocolateboy <chocolate@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.92'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-PMSEncoder
no_index:
  directory:
    - conf
    - inc
    - t
requires:
  File::HomeDir: 0.89
  File::ShareDir: 1.01
  HTTP::Lite: 2.2
  IO::All: 0.39
  IPC::Cmd: 0.56
  List::MoreUtils: 0.22
  Mouse: 0.49
  Path::Class: 0.18
  YAML::Tiny: 1.41
  perl: 5.10.0
resources:
  license: http://opensource.org/licenses/artistic-license-2.0.php
  repository: http://github.com/chocolateboy/pmsencoder
version: 0.60
